baseURL = "https://freesign.ru/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "Bigspring Hugo"
[markup.goldmark.renderer]
unsafe = true
